algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2021
// Seção de Declarações 
var
   primeiraNota, segundaNota, mediaNotas: real
inicio
// Seção de Comandos 
   Escreval("CALCULA MÉDIA DE 2 NOTAS")

   Escreva("Nota 1: ")
   Leia(primeiraNota)
   Escreva("Nota 2: ")
   Leia(segundaNota)
   
   mediaNotas <- ((primeiraNota + segundaNota) / 2)
   
   Escreva("A média entre", primeiraNota, " e", segundaNota, " é igual a", mediaNotas)

fimalgoritmo
