algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2021
// Seção de Declarações 
var
           fahrenheit, celsius: real
           
inicio
// Seção de Comandos 
   Escreva("Digite a temperatura em Fahrenheit: ")
   Leia(Fahrenheit)
   
   celsius <- (fahrenheit - 32) * 5/9)
   //celsius <-(fahrenheit - 32) / 1.8)
   
   Escreva("A temperatura em graus celsius é: ", celsius:4:1)
   

fimalgoritmo
