algoritmo "Fibonacci"
// Função :
// Autor :
// Data : 22/06/2021
// Seção de Declarações 
var
        fibo1, fibo2, soma, contador: inteiro
inicio
// Seção de Comandos 
         fibo1 <- 1
         
         Para contador <- 1 ate 10 passo 1 faca
         
              soma <- fibo1 + fibo2
              
              Escreva(soma)
              
              fibo1 <- fibo2
              fibo2 <- soma
         
         FimPara
         



fimalgoritmo
