algoritmo "RealParaDolar"
// Função :
// Autor :
// Data : 21/06/2021
// Seção de Declarações 
var
   reais, dolares, cotacao : real
inicio
// Seção de Comandos 

   Escreva("Digite a cotação atual do dolar: ")
   Leia(cotacao)
   Escreva("Digite a quantidade em reais: ")
   Leia(reais)

   dolares <- (reais / cotacao)                                    ]
   
   Escreva("R$", reais, " equivalem a: ", "U$", dolares, " dolares")


fimalgoritmo
